Cotya/magento-composer-installer

- src/MagentoHackathon/Composer/Magento/Plugin.php
This plugin does not work in PHP 5.3.
Closures (anonymous functions) are not bound to any scope in PHP 5.3. Therefore, you cannot use `static::` within a closure before PHP 5.4. Given that `composer.json` claims that this plugin works on PHP 5.3, this functionality needs to be re-factored.
> Re-factor closure to enable compatibility with PHP 5.3

- src/MagentoHackathon/Composer/Magento/Patcher/Bootstrap.php
- tests/MagentoHackathon/Composer/Magento/Patcher/BootstrapTest.php
Some fixes:
- Start bootstrap file with `<?php`
- Switch order of bootstrap's includes
- Otherwise, Mage.bootstrap.php tries to use `Mage` before Mage exists
- Add DS between `__DIR__` and file names
Also expanded testing a bit
- Ensure that the Mage class file is working
- Other files should be tested (parsed?) but how?
> Update Bootstrap file generation

- src/MagentoHackathon/Composer/Magento/Patcher/Bootstrap.php
- src/MagentoHackathon/Composer/Magento/Plugin.php
- src/MagentoHackathon/Composer/Magento/ProjectConfig.php
- tests/MagentoHackathon/Composer/Magento/Patcher/BootstrapTest.php
This PR adds the new _boolean_  `extra` param - `with-bootstrap-patch` -, which can control if the `Mage.php` is changed/patched. 
If this param isn't found in `extra`, it'll be assumed `false` - hence no patching by default.
> Create a new "extra" option flag to control patching of Mage.php (patching applied by default)

- phpunit.xml.dist
- tests/MagentoHackathon/Composer/FullStack/FullStackTest.php
- tests/MagentoHackathon/Composer/Magento/FullStack/AbstractTest.php
This does a couple of things:
- fixes `Output:
process for <code>composer.phar archive --format=zip --dir="../../../../tests/FullStackTest/artifact" -vvv</code> exited with 127: Command not found
Error Message:
sh: composer.phar: command not found`, for people who renamed their `composer.phar` to `composer` (like me)
- removed the *silent* exclusion of slow tests from `phpunit.xml.dist`, because it should be left to the devs decision (explicit exclusion)
- some common logic extracted into methods
- phpstorm automagically and conveniently removed all trailing whitespaces (so better use the `?w=1` trick to view this on github)
> Resolve composer executable name + some refactoring

- src/MagentoHackathon/Composer/Magento/ProjectConfig.php
- tests/MagentoHackathon/Composer/Magento/ModuleManagerTest.php
When using `\MagentoHackathon\Composer\Magento\ProjectConfig::getVendorDir()`, the passed array didn't contain the `vendor-dir` key (a sub-array of it did), so the default value was always returned (i.e. "vendor"), irrelevant of the configuration in "composer.json".
Also, the said method must always return the absolute path to the vendor folder, as it's the case with Composer.
----
Instantiation of the PluginConfig class is somewhat inconsistent:
```php
// \MagentoHackathon\Composer\Magento\Plugin::activate
$this->config = new ProjectConfig($composer->getPackage()->getExtra(), $composer->getConfig()->all());
```
or
```php
// \MagentoHackathon\Composer\Helper::__construct
$reader = new \Eloquent\Composer\Configuration\ConfigurationReader;
$composerJsonObject = …
```
> Fixes wrong value returned when getting the vendor dir through PluginConfig

- src/MagentoHackathon/Composer/Magento/ProjectConfig.php
Explodes on badly written unit tests.
> Check if vendor key exists, before usage

- CHANGELOG.md
- composer.json
- src/MagentoHackathon/Composer/Magento/InstalledPackage.php
- src/MagentoHackathon/Composer/Magento/InstalledPackageDumper.php
- src/MagentoHackathon/Composer/Magento/ModuleManager.php
- src/MagentoHackathon/Composer/Magento/Plugin.php
- src/MagentoHackathon/Composer/Magento/Repository/InstalledPackageFileSystemRepository.php
- src/MagentoHackathon/Composer/Magento/Repository/InstalledPackageRepositoryInterface.php
- tests/MagentoHackathon/Composer/Magento/ModuleManagerTest.php
- tests/MagentoHackathon/Composer/Magento/PluginTest.php
- tests/MagentoHackathon/Composer/Magento/Repository/InstalledFilesFilesystemRepositoryTest.php
I found the patch for #34 to be counter productive and it didn't really solve the issue of #7, more covered it up. 
This patch reverts #34 and provides a simpler patch.
When we ask for the installed packages from Composer [here](https://github.com/Cotya/magento-composer-installer/blob/3.0.4-beta1/src/MagentoHackathon/Composer/Magento/Plugin.php#L201) we get duplicate packages for packages which use branch aliasing. We get one instance of `AliasPackage` and one instance of `CompletePackage`, but these packages have the same name and therefore `ModuleManager` processes them as if they are different packages. First it will install one, then attempt to install the other, then the exception will be thrown noting that the package has already been installed (it has).
`dev-master` packages and …
> Alternate patch to #34 for fixing #7 and #33

- doc/FAQ.md
- src/MagentoHackathon/Composer/Magento/Plugin.php
- src/MagentoHackathon/Composer/Magento/ProjectConfig.php
The current version constantly suggests setting up repositories for packages.magento.com and packages.firegento.com. Packages.magento.com is only for Magento 2, so it's not always appropriate to suggest it. This pull request lets the user simply disable those suggestions via an extra config option.
> Optional suggest repo

- CHANGELOG.md
- src/MagentoHackathon/Composer/Magento/GitIgnore.php
- src/MagentoHackathon/Composer/Magento/Parser/PackageXmlParser.php
- tests/MagentoHackathon/Composer/Magento/GitIgnoreTest.php
- tests/MagentoHackathon/Composer/Magento/Parser/PackageXmlParserTest.php
Package XMl mappings have `./` prepended to them, because the base paths from `res/target.xml` are prepended to each mapping. This causes issues when updating the `gitignore` as the `gitignore` prepends `/` to the paths. This results in a path like `/./app/code/community/EcomDev/PHPUnitTest` in the `gitignore`. The fix as I see it is to just remove the first 2 characters of the file path from the mappings generated by `\MagentoHackathon\Composer\Magento\Parser\PackageXmlParser`. 
Fixes #48
> Fix package XML mappings

- CHANGELOG.md
- src/MagentoHackathon/Composer/Magento/Event/PackageUnInstallEvent.php
- src/MagentoHackathon/Composer/Magento/GitIgnoreListener.php
- src/MagentoHackathon/Composer/Magento/ModuleManager.php
- src/MagentoHackathon/Composer/Magento/Plugin.php
- tests/MagentoHackathon/Composer/Magento/GitIgnoreListenerTest.php
- tests/MagentoHackathon/Composer/Magento/PluginTest.php
Uninstalling does currently not trigger events for the git-ignore listener to be triggered. This fixes that with some slight amends.
> Remove gitignore entries when un-installing a package

- CHANGELOG.md
- src/MagentoHackathon/Composer/Magento/ModuleManager.php
- src/MagentoHackathon/Composer/Magento/Plugin.php
- src/MagentoHackathon/Composer/Magento/UnInstallStrategy/UnInstallStrategy.php
- tests/MagentoHackathon/Composer/Magento/UninstallStrategy/UnInstallStrategyTest.php
When uninstalling modules, empty directories are left. Traverse up to the root, removing each empty directory for each file which is removed. 
This will probably need rebasing after #50 and #49
> Remove empty directories up to the root dir

- CHANGELOG.md
- doc/Mapping.md
There was no documentation about how to enable the `package.xml` mapping. While I was in there adding it I also fixed up some formatting issues.
> Add documentation for package.xml mapping

- .travis.yml
We support 5.4 as minimum version so we should not allow failures on Travis. For the same reason there is no point running on 5.3
> 5.4 should not be in allowed failures & remove 5.3

- CHANGELOG.md
- src/MagentoHackathon/Composer/Magento/UnInstallStrategy/UnInstallStrategy.php
- tests/MagentoHackathon/Composer/Magento/UninstallStrategy/UnInstallStrategyTest.php
When updating a module, the uninstaller was removing files from the vendor folder which meant when it tried to install the new version right after, the files were missing.
When uninstalling modules, we should not follow symlinks.
> Stop uninstaller following symlinks

- src/MagentoHackathon/Composer/Magento/UnInstallStrategy/UnInstallStrategy.php
I think there's a bug when you call `composer run-script post-update-cmd -vvv -- --redeploy`. Error message is: `[InvalidArgumentException] The [path] directory does not exist.` This seems to happen when the module is installed according to composer, but was not deployed to the Magento installation for whatever reason.
This usually happens when you add module to your composer.json, switch Git branches, add it there as well, and run Composer update. The Magento composer installer plugin won't deploy because nothing has changed in the vendor folder, unless you run redeploy (and then this bug occurs).
Usually what I do, is clear the vendor directory (or the module that's causing the issue), run composer update (and optionally run redeploy to make sure the if vendor directory is in sync with …
> Added check to see if directory exists (for redeploy command)

- src/MagentoHackathon/Composer/Magento/Parser/PackageXmlParser.php
- tests/MagentoHackathon/Composer/Magento/Parser/PackageXmlParserTest.php
- tests/res/fixtures/PackageXmlNestedDirs.xml
* Replace double slashes in mappings
Sometimes dirs are mapped into empty dir tags
causing double slashes in the mapping.
> Resolve package.xml mappings edge case

- src/MagentoHackathon/Composer/Magento/Plugin.php
- tests/FullStackTest/home/composer.json
- tests/FullStackTest/magento-modules/composer_1.json
- tests/FullStackTest/magento-modules/composer_1_copy.json
- tests/FullStackTest/magento-modules/composer_1_copy_force.json
- tests/FullStackTest/magento-modules/composer_2.json
- tests/FullStackTest/magento-modules/composer_2_copy.json
- tests/FullStackTest/magento-modules/composer_2_copy_force.json
- tests/FullStackTest/magento/composer.json
- tests/MagentoHackathon/Composer/FullStack/Regression/Issue139Test.php
- tests/MagentoHackathon/Composer/FullStack/Regression/IssueC039Test.php
Since the [Composer beta1 release](https://github.com/composer/composer/releases/tag/1.0.0-beta1) of 03-03-2016 the use of unsecure url's is prohibited by default. See also the [documentation](https://getcomposer.org/doc/06-config.md#secure-http) of the `secure-http` config option.
This PR changes all uses of HTTP in this repository to HTTPS.
Note that this PR fixes a number of tests in the test suite, but not all: downloads of `connect20` packages still use HTTP; this should be fixed somewhere else.
> Use HTTPS for repository urls

- CHANGELOG.md
- src/MagentoHackathon/Composer/Magento/GitIgnore.php
- tests/MagentoHackathon/Composer/Magento/GitIgnoreTest.php
This modified GitIgnore processing has a different way of processing the single lines and avoids changing the layout, removing duplicate comments, whitelines etc. (issues of the current master).
Includes two new tests to assert this behaviour.
Fixes #83 as well.
> Modify GitIgnore processing to retain layout

- CHANGELOG.md
- README.md
- src/MagentoHackathon/Composer/Magento/ModuleManager.php
- src/MagentoHackathon/Composer/Magento/Plugin.php
- src/MagentoHackathon/Composer/Magento/ProjectConfig.php
- tests/MagentoHackathon/Composer/FullStack/Regression/IssueC065Test.php
- tests/MagentoHackathon/Composer/Magento/PluginTest.php
As the title says, this commit enables the magento-composer-installer to include the root package in deployment. To make use of this feature, it has to be explicitly configured in a project's `composer.json` (for reference see the addition to the readme file).
> added functionality to include root package when deploying modules

- composer.json
composer.json did wrongfully show PHP 5.4 as a supported version.
But PHP 5.4 is unsupported.
This is an easy fix by raising the version constraint from 5.4 to 5.5.
See https://github.com/Cotya/magento-composer-installer/issues/43#issuecomment-193961823
Ref: https://github.com/magento-hackathon/magento-composer-installer/issues/195 , #43
> Remove support for PHP 5.4

- CHANGELOG.md
- README.md
this snippet from the example in the README
```
"repositories": [
{
"type": "composer",
"url": "http://packages.firegento.com"
}
],
```
can cause this problem
changing the repository url to use https fixes this
```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
```
> repository url in example uses https

- src/MagentoHackathon/Composer/Magento/Patcher/Bootstrap.php
On system, where is open basedir setup for root web directory as most top, previous setup fails in fatal error.
This fix switched the order of file check and in case file match, second part of condition won`t be run. This fix error in these systems.
Tested many times.
> Fix Mage.php match for systems with open_basedir

- composer.json
Your requirements could not be resolved to an installable set of packages.
Problem 1
- magento-hackathon/magento-composer-installer 2.0.0 requires composer-plugin-api 1.0.0 -> no matching package found.
- magento-hackathon/magento-composer-installer 2.0.0 requires composer-plugin-api 1.0.0 -> no matching package found.
- magento-hackathon/magento-composer-installer 2.0.0 requires composer-plugin-api 1.0.0 -> no matching package found.
- Installation request for magento-hackathon/magento-composer-installer 2.0.0 -> satisfiable by magento-hackathon/magento-composer-installer[2.0.0].
> fixing bug with 1.1 composer

- src/MagentoHackathon/Composer/Magento/Deploystrategy/AbsoluteSymlink.php
- src/MagentoHackathon/Composer/Magento/Factory/DeploystrategyFactory.php
because the relative symlink strategy fails under certain circumstances.
> Add absolute symlink strategy 

- src/MagentoHackathon/Composer/Magento/Plugin.php
- src/MagentoHackathon/Composer/Magento/ProjectConfig.php
After recent events it should be awesome to have different strategies for dev and production.
When working locally you can now have any `extra` parameter, append  a `-dev` and these will overwrite the other setting.
For example:
```
....
"extra": {
"magento-deploystrategy": "copy",
"magento-deploystrategy-dev": "symlink",
}
...
```
> Added "-dev" for extra values

- README.md
I changed the README.md to use https by default. If you don't do this, Composer will refuse to install if you don't include the `secure-http: false` in your composer.json.
> Changed http to https

- src/MagentoHackathon/Composer/Magento/Deploystrategy/Symlink.php
- src/MagentoHackathon/Composer/Magento/UnInstallStrategy/UnInstallStrategy.php
there is problem with absolute links when using virtual machine with shared ntfs folders. 
absolute paths in ntfs symlinks does not apearing on vritual machine linux os. 
php symlinks supports only absolute paths for windows environment, but there is still way to use relative paths for symlinks. I implemented a litle workaround using native mklink command, i tested and it works great. 
also, there is problem duriong uninstallation. happens on windows while deleting symlinks with no targets. is_dir returns false for symlinks which linkling to unexisting folder. in this case i think it is fine if will try to remove it by using rmdir even if is_dir returned false.
do you think it doable?
> add workaround to handle windows symlinks

- src/MagentoHackathon/Composer/Magento/Plugin.php
In later PHP-versions attempts to access array offsets on nulls result in errors, which prevents any `composer update` commands from running, this PR fixes that.
> fix: avoid crashing on update if the rule does not contain a job

- src/MagentoHackathon/Composer/Magento/Plugin.php
Newer versions of Symfony Process requires an array as an constructor argument. 
Array was supported already in previous versions (since ~v4).
> Compatibility with newer versions of Symfony
